spring:
  datasource:
    username: root
    password: 041008Ys
    url: jdbc:mysql://localhost:3306/web
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy:  ant_path_matcher
  swagger:enable: true












